//SETTINGS

export const CHANGE_FOCUS_TIME = 'CHANGE_FOCUS_TIME'
export const CHANGE_ALARM_SOUND = 'CHANGE_ALARM_SOUND'


//COUNTER

export const SET_IS_COUNTING = 'SET_IS_COUNTING'
export const SET_IS_DURING_COUNTING = 'SET_IS_DURING_COUNTING'
export const SET_TIME_LEFT = 'SET_TIME_LEFT'