//SETTINGS

export const CHANGE_FOCUS_TIME = 'CHANGE_FOCUS_TIME'
export const CHANGE_ALARM_SOUND = 'CHANGE_ALARM_SOUND'


//STATS

export const FETCH_STATS = 'FETCH_STATS'
export const FETCH_STATS_FULFILLED = 'FETCH_STATS_FULFILLED'
export const FETCH_STATS_PENDING = 'FETCH_STATS_PENDING'
export const FETCH_STATS_REJECTED = 'FETCH_STATS_REJECTED'


//COUNTER

export const FETCH_LABELS_FULFILLED = 'FETCH_LABELS_FULFILLED'
export const FETCH_LABELS_PENDING = 'FETCH_LABELS_PENDING'
export const FETCH_LABELS_REJECTED = 'FETCH_LABELS_REJECTED'
export const SET_CURRENT_LABEL = 'SET_CURRENT_LABEL'
export const SET_IS_COUNTING = 'SET_IS_COUNTING'
export const SET_IS_DURING_COUNTING = 'SET_IS_DURING_COUNTING'
export const SET_TIME_LEFT = 'SET_TIME_LEFT'